/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicImport } from './routes/_public'
import { Route as PrivateImport } from './routes/_private'
import { Route as PublicIndexImport } from './routes/_public/index'
import { Route as PublicRegistrationImport } from './routes/_public/registration'
import { Route as PublicLoginImport } from './routes/_public/login'
import { Route as PublicForgotPasswordImport } from './routes/_public/forgot-password'
import { Route as PrivateDashboardImport } from './routes/_private/dashboard'
import { Route as PrivatePartiesIndexImport } from './routes/_private/parties/index'
import { Route as PrivateListsIndexImport } from './routes/_private/lists/index'
import { Route as PrivatePartiesNewImport } from './routes/_private/parties/new'
import { Route as PrivateListsNewImport } from './routes/_private/lists/new'
import { Route as PrivatePartiesPartyIdIndexImport } from './routes/_private/parties/$partyId/index'
import { Route as PrivateListsListIdIndexImport } from './routes/_private/lists/$listId/index'
import { Route as PrivatePartiesPartyIdEditImport } from './routes/_private/parties/$partyId/edit'
import { Route as PrivateListsListIdEditImport } from './routes/_private/lists/$listId/edit'

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const PublicIndexRoute = PublicIndexImport.update({
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)

const PublicRegistrationRoute = PublicRegistrationImport.update({
  path: '/registration',
  getParentRoute: () => PublicRoute,
} as any)

const PublicLoginRoute = PublicLoginImport.update({
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)

const PublicForgotPasswordRoute = PublicForgotPasswordImport.update({
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)

const PrivateDashboardRoute = PrivateDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivatePartiesIndexRoute = PrivatePartiesIndexImport.update({
  path: '/parties/',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateListsIndexRoute = PrivateListsIndexImport.update({
  path: '/lists/',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivatePartiesNewRoute = PrivatePartiesNewImport.update({
  path: '/parties/new',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateListsNewRoute = PrivateListsNewImport.update({
  path: '/lists/new',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivatePartiesPartyIdIndexRoute = PrivatePartiesPartyIdIndexImport.update(
  {
    path: '/parties/$partyId/',
    getParentRoute: () => PrivateRoute,
  } as any,
)

const PrivateListsListIdIndexRoute = PrivateListsListIdIndexImport.update({
  path: '/lists/$listId/',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivatePartiesPartyIdEditRoute = PrivatePartiesPartyIdEditImport.update({
  path: '/parties/$partyId/edit',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateListsListIdEditRoute = PrivateListsListIdEditImport.update({
  path: '/lists/$listId/edit',
  getParentRoute: () => PrivateRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardImport
      parentRoute: typeof PrivateImport
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordImport
      parentRoute: typeof PublicImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginImport
      parentRoute: typeof PublicImport
    }
    '/_public/registration': {
      id: '/_public/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof PublicRegistrationImport
      parentRoute: typeof PublicImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexImport
      parentRoute: typeof PublicImport
    }
    '/_private/lists/new': {
      id: '/_private/lists/new'
      path: '/lists/new'
      fullPath: '/lists/new'
      preLoaderRoute: typeof PrivateListsNewImport
      parentRoute: typeof PrivateImport
    }
    '/_private/parties/new': {
      id: '/_private/parties/new'
      path: '/parties/new'
      fullPath: '/parties/new'
      preLoaderRoute: typeof PrivatePartiesNewImport
      parentRoute: typeof PrivateImport
    }
    '/_private/lists/': {
      id: '/_private/lists/'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof PrivateListsIndexImport
      parentRoute: typeof PrivateImport
    }
    '/_private/parties/': {
      id: '/_private/parties/'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PrivatePartiesIndexImport
      parentRoute: typeof PrivateImport
    }
    '/_private/lists/$listId/edit': {
      id: '/_private/lists/$listId/edit'
      path: '/lists/$listId/edit'
      fullPath: '/lists/$listId/edit'
      preLoaderRoute: typeof PrivateListsListIdEditImport
      parentRoute: typeof PrivateImport
    }
    '/_private/parties/$partyId/edit': {
      id: '/_private/parties/$partyId/edit'
      path: '/parties/$partyId/edit'
      fullPath: '/parties/$partyId/edit'
      preLoaderRoute: typeof PrivatePartiesPartyIdEditImport
      parentRoute: typeof PrivateImport
    }
    '/_private/lists/$listId/': {
      id: '/_private/lists/$listId/'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof PrivateListsListIdIndexImport
      parentRoute: typeof PrivateImport
    }
    '/_private/parties/$partyId/': {
      id: '/_private/parties/$partyId/'
      path: '/parties/$partyId'
      fullPath: '/parties/$partyId'
      preLoaderRoute: typeof PrivatePartiesPartyIdIndexImport
      parentRoute: typeof PrivateImport
    }
  }
}

// Create and export the route tree

interface PrivateRouteChildren {
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivateListsNewRoute: typeof PrivateListsNewRoute
  PrivatePartiesNewRoute: typeof PrivatePartiesNewRoute
  PrivateListsIndexRoute: typeof PrivateListsIndexRoute
  PrivatePartiesIndexRoute: typeof PrivatePartiesIndexRoute
  PrivateListsListIdEditRoute: typeof PrivateListsListIdEditRoute
  PrivatePartiesPartyIdEditRoute: typeof PrivatePartiesPartyIdEditRoute
  PrivateListsListIdIndexRoute: typeof PrivateListsListIdIndexRoute
  PrivatePartiesPartyIdIndexRoute: typeof PrivatePartiesPartyIdIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivateListsNewRoute: PrivateListsNewRoute,
  PrivatePartiesNewRoute: PrivatePartiesNewRoute,
  PrivateListsIndexRoute: PrivateListsIndexRoute,
  PrivatePartiesIndexRoute: PrivatePartiesIndexRoute,
  PrivateListsListIdEditRoute: PrivateListsListIdEditRoute,
  PrivatePartiesPartyIdEditRoute: PrivatePartiesPartyIdEditRoute,
  PrivateListsListIdIndexRoute: PrivateListsListIdIndexRoute,
  PrivatePartiesPartyIdIndexRoute: PrivatePartiesPartyIdIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegistrationRoute: typeof PublicRegistrationRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegistrationRoute: PublicRegistrationRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof PublicRouteWithChildren
  '/dashboard': typeof PrivateDashboardRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/registration': typeof PublicRegistrationRoute
  '/': typeof PublicIndexRoute
  '/lists/new': typeof PrivateListsNewRoute
  '/parties/new': typeof PrivatePartiesNewRoute
  '/lists': typeof PrivateListsIndexRoute
  '/parties': typeof PrivatePartiesIndexRoute
  '/lists/$listId/edit': typeof PrivateListsListIdEditRoute
  '/parties/$partyId/edit': typeof PrivatePartiesPartyIdEditRoute
  '/lists/$listId': typeof PrivateListsListIdIndexRoute
  '/parties/$partyId': typeof PrivatePartiesPartyIdIndexRoute
}

export interface FileRoutesByTo {
  '': typeof PrivateRouteWithChildren
  '/dashboard': typeof PrivateDashboardRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/registration': typeof PublicRegistrationRoute
  '/': typeof PublicIndexRoute
  '/lists/new': typeof PrivateListsNewRoute
  '/parties/new': typeof PrivatePartiesNewRoute
  '/lists': typeof PrivateListsIndexRoute
  '/parties': typeof PrivatePartiesIndexRoute
  '/lists/$listId/edit': typeof PrivateListsListIdEditRoute
  '/parties/$partyId/edit': typeof PrivatePartiesPartyIdEditRoute
  '/lists/$listId': typeof PrivateListsListIdIndexRoute
  '/parties/$partyId': typeof PrivatePartiesPartyIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/registration': typeof PublicRegistrationRoute
  '/_public/': typeof PublicIndexRoute
  '/_private/lists/new': typeof PrivateListsNewRoute
  '/_private/parties/new': typeof PrivatePartiesNewRoute
  '/_private/lists/': typeof PrivateListsIndexRoute
  '/_private/parties/': typeof PrivatePartiesIndexRoute
  '/_private/lists/$listId/edit': typeof PrivateListsListIdEditRoute
  '/_private/parties/$partyId/edit': typeof PrivatePartiesPartyIdEditRoute
  '/_private/lists/$listId/': typeof PrivateListsListIdIndexRoute
  '/_private/parties/$partyId/': typeof PrivatePartiesPartyIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/registration'
    | '/'
    | '/lists/new'
    | '/parties/new'
    | '/lists'
    | '/parties'
    | '/lists/$listId/edit'
    | '/parties/$partyId/edit'
    | '/lists/$listId'
    | '/parties/$partyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/registration'
    | '/'
    | '/lists/new'
    | '/parties/new'
    | '/lists'
    | '/parties'
    | '/lists/$listId/edit'
    | '/parties/$partyId/edit'
    | '/lists/$listId'
    | '/parties/$partyId'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/dashboard'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/registration'
    | '/_public/'
    | '/_private/lists/new'
    | '/_private/parties/new'
    | '/_private/lists/'
    | '/_private/parties/'
    | '/_private/lists/$listId/edit'
    | '/_private/parties/$partyId/edit'
    | '/_private/lists/$listId/'
    | '/_private/parties/$partyId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_private",
        "/_public"
      ]
    },
    "/_private": {
      "filePath": "_private.tsx",
      "children": [
        "/_private/dashboard",
        "/_private/lists/new",
        "/_private/parties/new",
        "/_private/lists/",
        "/_private/parties/",
        "/_private/lists/$listId/edit",
        "/_private/parties/$partyId/edit",
        "/_private/lists/$listId/",
        "/_private/parties/$partyId/"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/forgot-password",
        "/_public/login",
        "/_public/registration",
        "/_public/"
      ]
    },
    "/_private/dashboard": {
      "filePath": "_private/dashboard.tsx",
      "parent": "/_private"
    },
    "/_public/forgot-password": {
      "filePath": "_public/forgot-password.tsx",
      "parent": "/_public"
    },
    "/_public/login": {
      "filePath": "_public/login.tsx",
      "parent": "/_public"
    },
    "/_public/registration": {
      "filePath": "_public/registration.tsx",
      "parent": "/_public"
    },
    "/_public/": {
      "filePath": "_public/index.tsx",
      "parent": "/_public"
    },
    "/_private/lists/new": {
      "filePath": "_private/lists/new.tsx",
      "parent": "/_private"
    },
    "/_private/parties/new": {
      "filePath": "_private/parties/new.tsx",
      "parent": "/_private"
    },
    "/_private/lists/": {
      "filePath": "_private/lists/index.tsx",
      "parent": "/_private"
    },
    "/_private/parties/": {
      "filePath": "_private/parties/index.tsx",
      "parent": "/_private"
    },
    "/_private/lists/$listId/edit": {
      "filePath": "_private/lists/$listId/edit.tsx",
      "parent": "/_private"
    },
    "/_private/parties/$partyId/edit": {
      "filePath": "_private/parties/$partyId/edit.tsx",
      "parent": "/_private"
    },
    "/_private/lists/$listId/": {
      "filePath": "_private/lists/$listId/index.tsx",
      "parent": "/_private"
    },
    "/_private/parties/$partyId/": {
      "filePath": "_private/parties/$partyId/index.tsx",
      "parent": "/_private"
    }
  }
}
ROUTE_MANIFEST_END */
